#################################################################
# Makefile generated by Xilinx Platform Studio 
# Project:/home/abazar63/hthread/src/platforms/xilinx/vc707_pr_smp1/design/system.xmp
#
# WARNING : This file will be re-generated every time a command
# to run a make target is invoked. So, any changes made to this  
# file manually, will be lost when make is invoked next. 
#################################################################

XILINX_EDK_DIR = /opt/Xilinx/14.7/ISE_DS/EDK

SYSTEM = system

MHSFILE = system.mhs

FPGA_ARCH = virtex7

DEVICE = xc7vx485tffg1761-2

INTSTYLE = default

XPS_HDL_LANG = vhdl
GLOBAL_SEARCHPATHOPT = 
PROJECT_SEARCHPATHOPT =  -lp /home/abazar63/hthread/src/hardware/

SEARCHPATHOPT = $(PROJECT_SEARCHPATHOPT) $(GLOBAL_SEARCHPATHOPT)

SUBMODULE_OPT = 

PLATGEN_OPTIONS = -p $(DEVICE) -lang $(XPS_HDL_LANG) -intstyle $(INTSTYLE) $(SEARCHPATHOPT) $(SUBMODULE_OPT) -msg __xps/ise/xmsgprops.lst -parallel yes

OBSERVE_PAR_OPTIONS = -error no

MICROBLAZE_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/microblaze/mb_bootloop.elf
MICROBLAZE_BOOTLOOP_LE = $(XILINX_EDK_DIR)/sw/lib/microblaze/mb_bootloop_le.elf
PPC405_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/ppc405/ppc_bootloop.elf
PPC440_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/ppc440/ppc440_bootloop.elf
BOOTLOOP_DIR = bootloops

MICROBLAZE_1_BOOTLOOP = $(BOOTLOOP_DIR)/microblaze_1.elf

MICROBLAZE_0_BOOTLOOP = $(BOOTLOOP_DIR)/microblaze_0.elf

BRAMINIT_ELF_IMP_FILES = $(MICROBLAZE_1_BOOTLOOP) $(MICROBLAZE_0_BOOTLOOP)
BRAMINIT_ELF_IMP_FILE_ARGS = -pe microblaze_1 $(MICROBLAZE_1_BOOTLOOP) -pe microblaze_0 $(MICROBLAZE_0_BOOTLOOP)

BRAMINIT_ELF_SIM_FILES = $(MICROBLAZE_1_BOOTLOOP) $(MICROBLAZE_0_BOOTLOOP)
BRAMINIT_ELF_SIM_FILE_ARGS = -pe microblaze_1 $(MICROBLAZE_1_BOOTLOOP) -pe microblaze_0 $(MICROBLAZE_0_BOOTLOOP)

SIM_CMD = vsim

BEHAVIORAL_SIM_SCRIPT = simulation/behavioral/$(SYSTEM)_setup.do

STRUCTURAL_SIM_SCRIPT = simulation/structural/$(SYSTEM)_setup.do

TIMING_SIM_SCRIPT = simulation/timing/$(SYSTEM)_setup.do

DEFAULT_SIM_SCRIPT = $(BEHAVIORAL_SIM_SCRIPT)

SIMGEN_OPTIONS = -p $(DEVICE) -lang $(XPS_HDL_LANG) -intstyle $(INTSTYLE) $(SEARCHPATHOPT) $(BRAMINIT_ELF_SIM_FILE_ARGS) -msg __xps/ise/xmsgprops.lst -s mgm


CORE_STATE_DEVELOPMENT_FILES = /opt/Xilinx/14.7/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/proc_common_pkg.vhd \
/opt/Xilinx/14.7/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/ipif_pkg.vhd \
/opt/Xilinx/14.7/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/or_muxcy.vhd \
/opt/Xilinx/14.7/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/or_gate128.vhd \
/opt/Xilinx/14.7/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/family_support.vhd \
/opt/Xilinx/14.7/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/pselect_f.vhd \
/opt/Xilinx/14.7/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/counter_f.vhd \
/opt/Xilinx/14.7/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/cntr_incr_decr_addn_f.vhd \
/opt/Xilinx/14.7/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/muxf_struct_f.vhd \
/opt/Xilinx/14.7/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/dynshreg_f.vhd \
/opt/Xilinx/14.7/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/srl_fifo_rbu_f.vhd \
/opt/Xilinx/14.7/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/srl_fifo_f.vhd \
/opt/Xilinx/14.7/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/soft_reset.vhd \
/opt/Xilinx/14.7/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/plbv46_slave_single_v1_01_a/hdl/vhdl/plb_address_decoder.vhd \
/opt/Xilinx/14.7/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/plbv46_slave_single_v1_01_a/hdl/vhdl/plb_slave_attachment.vhd \
/opt/Xilinx/14.7/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/plbv46_slave_single_v1_01_a/hdl/vhdl/plbv46_slave_single.vhd \
pcores/plb_thread_manager_v1_00_a/hdl/vhdl/infer_bram_dual_port.vhd \
pcores/plb_thread_manager_v1_00_a/hdl/vhdl/user_logic.vhd \
pcores/plb_thread_manager_v1_00_a/hdl/vhdl/plb_thread_manager.vhd \
/opt/Xilinx/14.7/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/plbv46_master_single_v1_01_a/hdl/vhdl/data_width_adapter.vhd \
/opt/Xilinx/14.7/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/plbv46_master_single_v1_01_a/hdl/vhdl/data_mirror_128.vhd \
/opt/Xilinx/14.7/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/plbv46_master_single_v1_01_a/hdl/vhdl/plbv46_master_single.vhd \
pcores/plb_sync_manager_v1_00_a/hdl/vhdl/common.vhd \
pcores/plb_sync_manager_v1_00_a/hdl/vhdl/lock_fsm.vhd \
pcores/plb_sync_manager_v1_00_a/hdl/vhdl/unlock_fsm.vhd \
pcores/plb_sync_manager_v1_00_a/hdl/vhdl/trylock_fsm.vhd \
pcores/plb_sync_manager_v1_00_a/hdl/vhdl/owner_fsm.vhd \
pcores/plb_sync_manager_v1_00_a/hdl/vhdl/kind_fsm.vhd \
pcores/plb_sync_manager_v1_00_a/hdl/vhdl/count_fsm.vhd \
pcores/plb_sync_manager_v1_00_a/hdl/vhdl/result_fsm.vhd \
pcores/plb_sync_manager_v1_00_a/hdl/vhdl/mutex_store.vhd \
pcores/plb_sync_manager_v1_00_a/hdl/vhdl/thread_store.vhd \
pcores/plb_sync_manager_v1_00_a/hdl/vhdl/send_store.vhd \
pcores/plb_sync_manager_v1_00_a/hdl/vhdl/slave.vhd \
pcores/plb_sync_manager_v1_00_a/hdl/vhdl/master.vhd \
pcores/plb_sync_manager_v1_00_a/hdl/vhdl/user_logic.vhd \
pcores/plb_sync_manager_v1_00_a/hdl/vhdl/plb_sync_manager.vhd \
pcores/plb_scheduler_v1_00_a/hdl/vhdl/infer_bram.vhd \
pcores/plb_scheduler_v1_00_a/hdl/vhdl/parallel.vhd \
pcores/plb_scheduler_v1_00_a/hdl/vhdl/user_logic.vhd \
pcores/plb_scheduler_v1_00_a/hdl/vhdl/plb_scheduler.vhd \
pcores/plb_hthreads_timer_v1_00_a/hdl/vhdl/user_logic.vhd \
pcores/plb_hthreads_timer_v1_00_a/hdl/vhdl/plb_hthreads_timer.vhd \
pcores/plb_hthread_reset_core_v1_00_a/hdl/vhdl/user_logic.vhd \
pcores/plb_hthread_reset_core_v1_00_a/hdl/vhdl/plb_hthread_reset_core.vhd \
/opt/Xilinx/14.7/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/fsl_v20_v2_11_f/hdl/vhdl/async_fifo_bram.vhd \
/opt/Xilinx/14.7/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/fsl_v20_v2_11_f/hdl/vhdl/async_fifo.vhd \
/opt/Xilinx/14.7/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/fsl_v20_v2_11_f/hdl/vhdl/gen_srlfifo.vhd \
/opt/Xilinx/14.7/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/fsl_v20_v2_11_f/hdl/vhdl/gen_sync_bram.vhd \
/opt/Xilinx/14.7/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/fsl_v20_v2_11_f/hdl/vhdl/gen_sync_dpram.vhd \
/opt/Xilinx/14.7/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/fsl_v20_v2_11_f/hdl/vhdl/sync_fifo.vhd \
/opt/Xilinx/14.7/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/fsl_v20_v2_11_f/hdl/vhdl/fsl_v20.vhd \
pcores/plb_cond_vars_v1_00_a/hdl/vhdl/condvar.vhd \
pcores/plb_cond_vars_v1_00_a/hdl/vhdl/user_logic.vhd \
pcores/plb_cond_vars_v1_00_a/hdl/vhdl/plb_cond_vars.vhd

WRAPPER_NGC_FILES = implementation/system_vhwti_local_cntlr_1_wrapper.ngc \
implementation/system_vhwti_lite_wrapper.ngc \
implementation/system_vhwti_global_cntlr_1_wrapper.ngc \
implementation/system_vhwti_bram_1_wrapper.ngc \
implementation/system_thread_manager_wrapper.ngc \
implementation/system_sync_manager_wrapper.ngc \
implementation/system_scheduler_wrapper.ngc \
implementation/system_proc_sys_reset_0_wrapper.ngc \
implementation/system_plbv46_axi_bridge_0_wrapper.ngc \
implementation/system_plb_hthreads_timer_0_wrapper.ngc \
implementation/system_plb_hthread_reset_core_0_wrapper.ngc \
implementation/system_microblaze_1_ilmb_wrapper.ngc \
implementation/system_microblaze_1_i_bram_ctrl_wrapper.ngc \
implementation/system_microblaze_1_dlmb_wrapper.ngc \
implementation/system_microblaze_1_d_bram_ctrl_wrapper.ngc \
implementation/system_microblaze_1_bram_block_wrapper.ngc \
implementation/system_microblaze_1_wrapper.ngc \
implementation/system_microblaze_0_ilmb_wrapper.ngc \
implementation/system_microblaze_0_i_bram_ctrl_wrapper.ngc \
implementation/system_microblaze_0_dlmb_wrapper.ngc \
implementation/system_microblaze_0_d_bram_ctrl_wrapper.ngc \
implementation/system_microblaze_0_bram_block_wrapper.ngc \
implementation/system_microblaze_0_wrapper.ngc \
implementation/system_mb_acc1_rst_wrapper.ngc \
implementation/system_mb_acc1_wrapper.ngc \
implementation/system_main_vhwti_axi_bridge_wrapper.ngc \
implementation/system_main_dram_axi_bridge_wrapper.ngc \
implementation/system_main_bus_wrapper.ngc \
implementation/system_hw_acc_1_wrapper.ngc \
implementation/system_group_lite_1_wrapper.ngc \
implementation/system_group_1_main_axi_bridge_wrapper.ngc \
implementation/system_group_1_ddr_axi_bridge_wrapper.ngc \
implementation/system_debug_module_wrapper.ngc \
implementation/system_ddr_bus_wrapper.ngc \
implementation/system_core_bus_wrapper.ngc \
implementation/system_cond_vars_wrapper.ngc \
implementation/system_clock_generator_0_wrapper.ngc \
implementation/system_bramc1_cntlr_wrapper.ngc \
implementation/system_bramb1_cntlr_wrapper.ngc \
implementation/system_bramc1_wrapper.ngc \
implementation/system_bramb1_wrapper.ngc \
implementation/system_brama1_cntlr_wrapper.ngc \
implementation/system_brama1_wrapper.ngc \
implementation/system_axi_timer_0_wrapper.ngc \
implementation/system_axi_plbv46_bridge_0_wrapper.ngc \
implementation/system_axi_intc_0_wrapper.ngc \
implementation/system_axi_hwicap_0_wrapper.ngc \
implementation/system_axi_cdma_0_wrapper.ngc \
implementation/system_acc_mb1_wrapper.ngc \
implementation/system_rs232_uart_1_wrapper.ngc \
implementation/system_ddr3_sdram_wrapper.ngc

POSTSYN_NETLIST = implementation/$(SYSTEM).ngc

SYSTEM_BIT = implementation/$(SYSTEM).bit

DOWNLOAD_BIT = implementation/download.bit

SYSTEM_ACE = implementation/$(SYSTEM).ace

UCF_FILE = data/system.ucf

BMM_FILE = implementation/$(SYSTEM).bmm

BITGEN_UT_FILE = etc/bitgen.ut

XFLOW_OPT_FILE = etc/fast_runtime.opt
XFLOW_DEPENDENCY = __xps/xpsxflow.opt $(XFLOW_OPT_FILE)

XPLORER_DEPENDENCY = __xps/xplorer.opt
XPLORER_OPTIONS = -p $(DEVICE) -uc $(SYSTEM).ucf -bm $(SYSTEM).bmm -max_runs 7

FPGA_IMP_DEPENDENCY = $(BMM_FILE) $(POSTSYN_NETLIST) $(UCF_FILE) $(XFLOW_DEPENDENCY)

SDK_EXPORT_DIR = SDK/SDK_Export/hw
SYSTEM_HW_HANDOFF = $(SDK_EXPORT_DIR)/$(SYSTEM).xml
SYSTEM_HW_HANDOFF_BIT = $(SDK_EXPORT_DIR)/$(SYSTEM).bit
SYSTEM_HW_HANDOFF_BMM = $(SDK_EXPORT_DIR)/$(SYSTEM)_bd.bmm
SYSTEM_HW_HANDOFF_DEP = $(SYSTEM_HW_HANDOFF) $(SYSTEM_HW_HANDOFF_BIT) $(SYSTEM_HW_HANDOFF_BMM)
