# ==============================================================
# File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
# Version: 2014.2
# Copyright (C) 2014 Xilinx Inc. All rights reserved.
# 
# ==============================================================


/opt/Xilinx/Vivado_HLS/2014.2/../../Vivado/2014.2/bin/vivado  -notrace -mode batch -source ipi_example.tcl -tclargs xc7k325tffg900-2 ../xilinx_com_hls_acc_vadd_1_0.zip
