# ==============================================================
# File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
# Version: 2014.2
# Copyright (C) 2014 Xilinx Inc. All rights reserved.
# 
# ==============================================================

#
# Settings for Vivado implementation flow
#
set top_module vectoradd
set language verilog
set family virtex7
set device xc7vx485t
set package ffg1761
set speed -2
set clock ap_clk
set fsm_ext "auto"

# For customizing the implementation flow
set add_io_buffers false ;# true|false
set comb_luts false      ;# true|false
