# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7k325tffg900-2
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:kc705:part0:1.0 [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]
read_verilog -library xil_defaultlib /home/senma/Desktop/heterogeneous_hthreads_latest/src/hardware/MyRepository/pcores/vivado_cores/acc_vadd_hls/project/project.srcs/sources_1/imports/verilog/acc_vadd_hls.v
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/senma/Desktop/heterogeneous_hthreads_latest/src/hardware/MyRepository/pcores/vivado_cores/acc_vadd_hls/project/project.cache/wt [current_project]
set_property parent.project_dir /home/senma/Desktop/heterogeneous_hthreads_latest/src/hardware/MyRepository/pcores/vivado_cores/acc_vadd_hls/project [current_project]
catch { write_hwdef -file acc_vadd_hls.hwdef }
synth_design -top acc_vadd_hls -part xc7k325tffg900-2
write_checkpoint acc_vadd_hls.dcp
report_utilization -file acc_vadd_hls_utilization_synth.rpt -pb acc_vadd_hls_utilization_synth.pb
