// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.2
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#ifndef _acc_vadd_HH_
#define _acc_vadd_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct acc_vadd : public sc_module {
    // Port declarations 11
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst_n;
    sc_in< sc_lv<32> > sI1_TDATA;
    sc_in< sc_logic > sI1_TVALID;
    sc_out< sc_logic > sI1_TREADY;
    sc_in< sc_lv<32> > sI2_TDATA;
    sc_in< sc_logic > sI2_TVALID;
    sc_out< sc_logic > sI2_TREADY;
    sc_out< sc_lv<32> > mO1_TDATA;
    sc_out< sc_logic > mO1_TVALID;
    sc_in< sc_logic > mO1_TREADY;


    // Module declarations
    acc_vadd(sc_module_name name);
    SC_HAS_PROCESS(acc_vadd);

    ~acc_vadd();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    sc_signal< sc_lv<1> > ap_CS_fsm;
    sc_signal< bool > ap_sig_bdd_23;
    sc_signal< sc_logic > ap_sig_ioackin_mO1_TREADY;
    sc_signal< sc_logic > ap_reg_ioackin_mO1_TREADY;
    sc_signal< sc_lv<1> > ap_NS_fsm;
    sc_signal< bool > ap_sig_bdd_48;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<1> ap_ST_st1_fsm_0;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_sig_bdd_23();
    void thread_ap_sig_bdd_48();
    void thread_ap_sig_ioackin_mO1_TREADY();
    void thread_mO1_TDATA();
    void thread_mO1_TVALID();
    void thread_sI1_TREADY();
    void thread_sI2_TREADY();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
