#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst_n", 1, hls_in, -1, "", "", 1),
	Port_Property("cmd_TDATA", 32, hls_in, 0, "axis", "in_data", 1),
	Port_Property("cmd_TVALID", 1, hls_in, 0, "axis", "in_vld", 1),
	Port_Property("cmd_TREADY", 1, hls_out, 0, "axis", "in_acc", 1),
	Port_Property("resp_TDATA", 32, hls_out, 1, "axis", "out_data", 1),
	Port_Property("resp_TVALID", 1, hls_out, 1, "axis", "out_vld", 1),
	Port_Property("resp_TREADY", 1, hls_in, 1, "axis", "out_acc", 1),
	Port_Property("a_Addr_A", 32, hls_out, 2, "bram", "mem_address", 1),
	Port_Property("a_EN_A", 1, hls_out, 2, "bram", "mem_ce", 1),
	Port_Property("a_WEN_A", 4, hls_out, 2, "bram", "mem_we", 1),
	Port_Property("a_Din_A", 32, hls_out, 2, "bram", "mem_din", 1),
	Port_Property("a_Dout_A", 32, hls_in, 2, "bram", "mem_dout", 1),
	Port_Property("a_Clk_A", 1, hls_out, 2, "bram", "mem_clk", 1),
	Port_Property("a_Rst_A", 1, hls_out, 2, "bram", "mem_rst", 1),
	Port_Property("b_Addr_A", 32, hls_out, 3, "bram", "mem_address", 1),
	Port_Property("b_EN_A", 1, hls_out, 3, "bram", "mem_ce", 1),
	Port_Property("b_WEN_A", 4, hls_out, 3, "bram", "mem_we", 1),
	Port_Property("b_Din_A", 32, hls_out, 3, "bram", "mem_din", 1),
	Port_Property("b_Dout_A", 32, hls_in, 3, "bram", "mem_dout", 1),
	Port_Property("b_Clk_A", 1, hls_out, 3, "bram", "mem_clk", 1),
	Port_Property("b_Rst_A", 1, hls_out, 3, "bram", "mem_rst", 1),
	Port_Property("result_Addr_A", 32, hls_out, 4, "bram", "mem_address", 1),
	Port_Property("result_EN_A", 1, hls_out, 4, "bram", "mem_ce", 1),
	Port_Property("result_WEN_A", 4, hls_out, 4, "bram", "mem_we", 1),
	Port_Property("result_Din_A", 32, hls_out, 4, "bram", "mem_din", 1),
	Port_Property("result_Dout_A", 32, hls_in, 4, "bram", "mem_dout", 1),
	Port_Property("result_Clk_A", 1, hls_out, 4, "bram", "mem_clk", 1),
	Port_Property("result_Rst_A", 1, hls_out, 4, "bram", "mem_rst", 1),
};
const char* HLS_Design_Meta::dut_name = "acc_vadd_hls";
